print("Add two numbers")
a = input("Enter first number")
b = input("Enter second number")
a = int(a)
b = int(b)
print(a+b)
print("Divide two numbers")
c = input("Enter  dividend")
d = input("Enter  divisor")
c = int(c)
d = int(d)
print("The quotient  is ", c/d)
print("The remainder is", c%d)
